### ISSUE TITLE
Task list for converting from WG to Collab Space

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/standards#253]
The CPC would like to merge Collab Spaces and Working Groups (see rationale in [#1110](https://github.com/openjs-foundation/cross-project-council/issues/1110)).

iirc we had discussed that and agreed to it in a WG meeting a while back, but I couldn't find a note of it in the meeting minutes. So this is a formal request for the WG to OK this migration.
```[tasklist]
### Tasks
- [ ] Update all references from WG to Collab Space
- [ ] Document Decisions that have been delegated to the Collab Space
- [ ] Add to list of OpenJS Collab Spaces
```

**Comment by ljharb** [comment]
As long as it doesn’t diminish the autonomy of the group, I’m fine with the change.
